version: '3.3'

volumes:
  postgres_data:
  static_value:
  media_value:

services:
  db:
    image: postgres:13.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env.example

  app:
    build: .
    depends_on:
      - db
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    ports:
      - "8000:8000"
    env_file:
      - .env.example

  nginx:
    image: nginx:1.23.2-alpine
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    ports:
      - "80:80"
    env_file:
      - .env.example
